spring:
  application:
    name: sqs-demo
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
management:
    endpoints:
      web:
        exposure:
            include: beans
server:
  port: 8081